### ISSUE TITLE
Drop rustc-serialize dependency

### ISSUE THREAD

**Issue by dtolnay** [mit-pdos/distributary#17]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

Is there any functionality you would require from another library before this would be possible?

**Comment by jonhoo** [comment]
Thanks @dtolnay! I'm aware it has been deprecated. It's a bit finicky to remove because we want a different serialization strategy to be used when serializing to JSON versus when serializing using `bincode`. I don't know if there's an easy way to do that that I've overlooked?

**Comment by dtolnay** [comment]
I didn't look at the codebase too closely but maybe something like this? #18
